# authors:
#   <author>:
#     name: string        # Author name
#     description: string # Author description
#     avatar: url         # Author avatar
#     slug: url           # Author profile slug
#     url: url            # Author website URL

authors:
  pastoor:
    name: De Pastoor
    description: Sinds het overlijden van Pastoor de Jong viert Pastoor Meijer de Mis in onze parochie.
    avatar: https://katholiekgorinchem.nl/assets/authors/pastoor.png
    # slug: url
    # url: url

  pastoordejong:
    name: Pastoor de Jong       
    description: Pastoor de Jong was onze parochiepriester tot aan zijn overlijden op 16 november 2025.        
    avatar: https://katholiekgorinchem.nl/assets/authors/pastoor.jpeg
    # slug: url
    # url: url

  olivier:
    name: Olivier Spoor
    description: Beheerder van de website en redactielid.
    avatar: https://katholiekgorinchem.nl/assets/authors/olivier.jpeg
    # slug: url
    # url: url

  Kevin:
    name: Kevin
    description: Sinds 202 lid van de parochie.
    avatar: /assets/authors/kevin.png
    # slug: url
    # url: url

  bestuur:
    name: Parochiebestuur
    description: Het bestuur
    avatar: https://katholiekgorinchem.nl/assets/authors/redactie_icon.png
    # slug: url           # Author profile slug
    # url: url            # Author website URL

  vdakker:
    name: Yvonne van den Akker-Savelsbergh
    description: exegete Nieuwe Testament
    avatar: https://katholiekgorinchem.nl/assets/authors/yvonne.jpeg
    # slug: url           # Author profile slug
    # url: url            # Author website URL

  bisdom:
    name: Bisdom Rotterdam
    description: De Kerk van Rotterdam is een netwerk van liefde tot opbouw van een beschaving van liefde. Het bisdom wordt geleid door bisschop Van den Hende
    avatar: https://katholiekgorinchem.nl/assets/authors/bisdomrotterdam.jpg
    # slug: url           # Author profile slug
    # url: url            # Author website URL

